---
# handlers file for revenni.base

- name: postfix | sasl_postmap
  command: postmap /etc/postfix/sasl/sasl_passwd

- name: postfix | restart
  systemd:
    name: postfix
    state: restarted
    enabled: yes
